name: Build Client

on: pull_request

jobs:
  build-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: cd packages/client && npm install

  validate-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: EsLint Validation
        run: cd packages/client && npm run lint
