name: Client - Validate ESLint

on:
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: ./packages/client

jobs:
  validate-eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ./packages/client/.nvmrc

      - name: Install Dependencies
        run: npm ci

      - name: ESLint Validation
        run: npm run lint
